// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // DATABASE_URL is Supabase's pooled PgBouncer connection (port 6543) — fine for the
    // runtime client, but schema-engine DDL (db push/migrate) needs the direct, non-pooled
    // connection (port 5432) or it hangs indefinitely.
    directUrl: process.env["DIRECT_URL"],
  },
});
